[tool.black]
line-length = 128
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | _build
  | buck-out
  | build
  | dist
)/
'''
[tool.pytest.ini_options]
norecursedirs = "a2lparser/unittests"
[tool.pylint.messages_control]
max-line-length = 128
