name: build

# Controls when the action will run. 
on: push

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE and install python
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      # Set up virtual environment
      - name: Set up virtual environment
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
      - name: Activate virtual environment
        run: source .venv/bin/activate
      # Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install setuptools wheel build
      # Building the package
      - name: Build package
        run: |
          python -m build
      # Installing package
      - name: Install package
        run: |
          pip install dist/*.whl
      # Running a2lparser.
      - name: Print package version
        run: |
          a2lparser --version || exit 1
