name: pypi

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  #################
  # Windows Build #
  #################
  build-Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [2.7, 3.11]

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE and install python
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Set up virtual environment
      - name: Install virtualenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
      - name: Create virtual environment
        run: |
          virtualenv .venv
          cmd.exe \c call .venv\Scripts\activate.bat

      # Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install setuptools wheel

      # Building the package
      - name: Build package
        run: |
          python -m pip install .

      # Running a2lparser unittests.
      - name: Test the package
        run: |
          a2lparser --testcases

  ###############
  # Linux Build #
  ###############
  build-Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.11]

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE and install python
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Set up virtual environment
      - name: Install virtualenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
      - name: Create virtual environment
        run: |
          virtualenv .venv
          source .venv/bin/activate

      # Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install setuptools wheel

      # Building the package
      - name: Build package
        run: |
          python -m pip install .

      # Running a2lparser unittests.
      - name: Test the package
        run: |
          a2lparser --testcases
